// Guards against silent coverage regressions in backend/services, the package
// agent_docs/HEALTH_CHECKLIST.md tracks. Same shape as the bundle budget
// (frontend/scripts/check-bundle-size.mjs): a script owns the threshold, and both
// .claude/suite.json and CI call it by name, so /suite-kit:health enforces it too.
//
// Written in Go rather than as a shell step so one implementation serves every
// platform. The PowerShell version this replaces was Windows-only and needed its
// arguments quoted, because PowerShell splits an unquoted native argument on '=' —
// `go tool cover -func=x` came back "too many arguments".
//
// Deliberately *not* implemented with testing.Coverage() in a TestMain, which
// would have ridden the existing `go test` gate with no extra command. It reports
// a different number: 33.5% against the 36.7% `go test -cover` reports for the
// same run, because it is a pre-1.20 API the coverage redesign left behind. Its
// own doc comment warns it "is not a replacement for the reports generated by
// 'go test -cover' and 'go tool cover'". A floor has to be measured the same way
// the number people quote is measured.
//
// Run: go run ./scripts/coverage-floor
package main

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strconv"
)

// The package this floor is about. Scoped rather than ./... on purpose: the repo
// root and backend/models carry no test files, so an all-packages figure would be
// diluted by packages the floor is not about.
const targetPackage = "./backend/services/"

// Floor = the last measured figure minus a little headroom, so an unrelated
// refactor does not redden the build. It is a ratchet: raise it when coverage
// rises, never lower it to make a red build green.
//
//	36.7% -> floor 35.0  the backup/config-editor/RCON tests
//	38.0% -> floor 36.0  ConfigService and WriteDataFile tests
//	40.1% -> floor 38.0  console split-func and streamOutput tests (#112)
//	41.1% -> floor 39.0  atomic-write and world-duplication tests (#116, #115)
//
// Coverage is a proxy, not the goal. A test that would have caught a real bug is
// worth more than one that only moves this number.
const floorPercent = 39.0

// Matches the tail of `go test -cover` output: "coverage: 36.7% of statements".
var reCoverage = regexp.MustCompile(`coverage:\s+([0-9.]+)%\s+of\s+statements`)

func main() {
	cmd := exec.Command("go", "test", "-cover", targetPackage)
	out, err := cmd.CombinedOutput()
	// Print the test output either way: when tests fail, that is the thing worth
	// reading, not the coverage number.
	os.Stdout.Write(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "coverage floor: tests failed, coverage not judged\n")
		os.Exit(1)
	}

	match := reCoverage.FindStringSubmatch(string(out))
	if match == nil {
		// A check that could not run is a failure to report, not a silent pass.
		fmt.Fprintf(os.Stderr, "coverage floor: no coverage line found in the output of "+
			"`go test -cover %s`\n", targetPackage)
		os.Exit(1)
	}

	got, err := strconv.ParseFloat(match[1], 64)
	if err != nil {
		fmt.Fprintf(os.Stderr, "coverage floor: could not parse %q as a percentage: %v\n",
			match[1], err)
		os.Exit(1)
	}

	if got < floorPercent {
		fmt.Fprintf(os.Stderr, "\ncoverage floor: %.1f%% is below the required %.1f%%\n",
			got, floorPercent)
		fmt.Fprintln(os.Stderr, "Add tests for what you changed, or justify moving the floor.")
		os.Exit(1)
	}

	fmt.Printf("coverage floor: %.1f%% meets the %.1f%% minimum\n", got, floorPercent)
}
