/* The config tile's file tree and the contents behind it.
 *
 * This tile is the one that reads as *stuck* rather than empty without a
 * fixture: the compact view renders "Loading…" for as long as rawContent is
 * null, with no error path, so an unanswered ReadConfigFile leaves a spinner
 * up forever. server.properties therefore has to be real enough to parse —
 * ConfigSummary picks its rows out of ORDERED_KEYS by looking them up in the
 * file, and shows only the keys that are actually present.
 *
 * The formats are spread on purpose: `properties`, `yaml` and `json` each
 * drive a different CodeMirror language in the maximized editor, and only some
 * of them offer the form view.
 */

import { daysAgo, hoursAgo, minutesAgo } from "./server.js";

export const CONFIG_FILES = [
  {
    relPath: "server.properties",
    name: "server.properties",
    category: "server",
    source: "",
    format: "properties",
    sizeBytes: 1428,
    modified: hoursAgo(4),
  },
  {
    relPath: "bukkit.yml",
    name: "bukkit.yml",
    category: "server",
    source: "",
    format: "yaml",
    sizeBytes: 812,
    modified: daysAgo(12),
  },
  {
    relPath: "spigot.yml",
    name: "spigot.yml",
    category: "server",
    source: "",
    format: "yaml",
    sizeBytes: 2140,
    modified: daysAgo(12),
  },
  {
    relPath: "config/paper-global.yml",
    name: "paper-global.yml",
    category: "server",
    source: "",
    format: "yaml",
    sizeBytes: 6204,
    modified: daysAgo(12),
  },
  {
    relPath: "plugins/LuckPerms/config.yml",
    name: "config.yml",
    category: "plugins",
    source: "LuckPerms",
    format: "yaml",
    sizeBytes: 3980,
    modified: daysAgo(5),
  },
  {
    relPath: "plugins/BlueMap/core.conf",
    name: "core.conf",
    category: "plugins",
    source: "BlueMap",
    format: "text",
    sizeBytes: 1105,
    modified: daysAgo(14),
  },
  {
    relPath: "plugins/Chunky/config.yml",
    name: "config.yml",
    category: "plugins",
    source: "Chunky",
    format: "yaml",
    sizeBytes: 460,
    modified: minutesAgo(50),
  },
];

const SERVER_PROPERTIES = `#Minecraft server properties
#Generated by Konnekt
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=true
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=Overworld
motd=\\u00A7aSurvival \\u00A78\\u00B7 \\u00A77running on Konnekt
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=normal
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=8
rcon.password=hunter2
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=true
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=true
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
`;

const BUKKIT_YML = `settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 15
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
`;

const PAPER_GLOBAL = `_version: 29
chunk-loading-basic:
  player-max-chunk-generate-rate: -1.0
  player-max-chunk-load-rate: 100.0
  player-max-chunk-send-rate: 75.0
collisions:
  enable-player-collisions: true
  send-full-pos-for-hard-colliding-entities: true
console:
  enable-brigadier-completions: true
  enable-brigadier-highlighting: true
  has-all-permissions: false
messages:
  kick:
    authentication-servers-down: <lang:multiplayer.disconnect.authservers_down>
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: <lang:multiplayer.disconnect.flying>
  no-permission: <red>I'm sorry, but you do not have permission.
packet-limiter:
  all-packets:
    action: KICK
    interval: 7.0
    max-packet-rate: 500.0
`;

const LUCKPERMS_CONFIG = `server: global
storage-method: h2
data:
  address: localhost
  database: minecraft
  username: root
  table-prefix: 'luckperms_'
sync-minutes: -1
messaging-service: auto
auto-op: false
enable-ops: true
commands-allow-op: true
group-name-rewrite: {}
primary-group-calculation: parents-by-weight
argument-based-command-permissions: false
`;

const CHUNKY_CONFIG = `version: 1
task:
  update-interval: 1
  quiet-interval: 60
  auto-save: 30
`;

const BLUEMAP_CORE = `accept-download: true
data: "bluemap"
render-thread-count: 2
metrics: true
log: {
    file: "bluemap/logs/debug.log"
    append: false
}
`;

const CONTENTS = {
  "server.properties": SERVER_PROPERTIES,
  "bukkit.yml": BUKKIT_YML,
  "spigot.yml": BUKKIT_YML,
  "config/paper-global.yml": PAPER_GLOBAL,
  "plugins/LuckPerms/config.yml": LUCKPERMS_CONFIG,
  "plugins/Chunky/config.yml": CHUNKY_CONFIG,
  "plugins/BlueMap/core.conf": BLUEMAP_CORE,
};

/** Reads a config file, or throws the way the Go side does for an unknown path. */
export function readConfigFile(relPath) {
  const body = CONTENTS[relPath];
  if (body === undefined) throw new Error(`config file not found: ${relPath}`);
  return body;
}
