import { describe, it, expect } from 'vitest'
import type { LayoutItem } from 'react-grid-layout'
import { DEFAULT_LAYOUT_PRESETS, COLS } from './constants'
import { TILE_REGISTRY } from '../tiles/registry'
import { TILE_SIZE, TILE_MIN, TILE_MAX, collides } from './gridSizing'

const KNOWN_IDS = new Set(TILE_REGISTRY.map((t) => t.id))

// 'Default' is hand-authored and deliberately uses the resize range; the rest
// are generated by tileGrid() at a single shared size, so only they can be held
// to uniformity.
const UNIFORM_PRESETS = new Set(['Console Focus', 'Compact', 'Essentials'])
const UNIFORM_SIZES = [TILE_SIZE, TILE_MIN]

describe('DEFAULT_LAYOUT_PRESETS', () => {
  for (const preset of DEFAULT_LAYOUT_PRESETS) {
    describe(preset.name, () => {
      const layout: LayoutItem[] = JSON.parse(preset.layout)

      it('references only known tile ids', () => {
        for (const item of layout) {
          expect(KNOWN_IDS.has(item.i)).toBe(true)
        }
      })

      it('sizes every tile within the shared min..max resize range', () => {
        for (const item of layout) {
          expect(item.w).toBeGreaterThanOrEqual(TILE_MIN.w)
          expect(item.w).toBeLessThanOrEqual(TILE_MAX.w)
          expect(item.h).toBeGreaterThanOrEqual(TILE_MIN.h)
          expect(item.h).toBeLessThanOrEqual(TILE_MAX.h)
        }
      })

      if (UNIFORM_PRESETS.has(preset.name)) {
        it('is generated at a single shared size', () => {
          for (const item of layout) {
            const matches = UNIFORM_SIZES.some((s) => s.w === item.w && s.h === item.h)
            expect(matches).toBe(true)
          }
          const distinctSizes = new Set(layout.map((l) => `${l.w}x${l.h}`))
          expect(distinctSizes.size).toBe(1)
        })
      }

      it('fits within the grid column count', () => {
        for (const item of layout) {
          expect(item.x + item.w).toBeLessThanOrEqual(COLS)
          expect(item.x).toBeGreaterThanOrEqual(0)
        }
      })

      it('has no overlapping tiles', () => {
        for (let i = 0; i < layout.length; i++) {
          for (let j = i + 1; j < layout.length; j++) {
            expect(collides(layout[i], layout[j])).toBe(false)
          }
        }
      })

      it('has no duplicate tile ids', () => {
        const ids = layout.map((l) => l.i)
        expect(new Set(ids).size).toBe(ids.length)
      })
    })
  }

  it('Default, Console Focus, and Compact include every registered tile', () => {
    const fullPresets = DEFAULT_LAYOUT_PRESETS.filter((p) => p.name !== 'Essentials')
    for (const preset of fullPresets) {
      const ids = new Set((JSON.parse(preset.layout) as LayoutItem[]).map((l) => l.i))
      expect(ids).toEqual(KNOWN_IDS)
    }
  })

  it('Essentials is a deliberately smaller subset', () => {
    const essentials = DEFAULT_LAYOUT_PRESETS.find((p) => p.name === 'Essentials')!
    const ids = (JSON.parse(essentials.layout) as LayoutItem[]).map((l) => l.i)
    expect(ids.length).toBeLessThan(KNOWN_IDS.size)
  })
})
